### ISSUE TITLE
plan what the app should be

### ISSUE THREAD

**Issue by ZooeyMiller** [ZooeyMiller/dyel#2]
i need to work out what this app will actually do, this involves:

- [ ] decide on basic functionality and raise them as issues/user stories #3
- [ ] decide on tech stack based on user stories. (FE will be preact) #4
- [ ] decide on architecture based on tech stack and user stories #5
- [ ] create initial wireframes with Gravit. #6
